### ISSUE TITLE
Comments and space are removed when sorting in yaml

### ISSUE THREAD

**Issue by ffflorian** [bennycode/sort-everything#1]
Given I have a yaml file with unsorted lines:

```yaml
variables:
  MY_VARIABLE: 'true'    # Comment 1
  OTHER_VARIABLE: 'true' # Comment 2
  BEST_VARIABLE: 'true'  # Comment 3
```

I select them and run Sort Everything, I receive this:

```yaml
variables:
BEST_VARIABLE: "true"
MY_VARIABLE: "true"
OTHER_VARIABLE: "true"
```

but I was expecting to receive this:

```yaml
variables:
  BEST_VARIABLE: 'true'  # Comment 3
  MY_VARIABLE: 'true'    # Comment 1
  OTHER_VARIABLE: 'true' # Comment 2
```

Whitespace being removed is a bit annoying, too, but nothing serious. But I don't want to lose those precious comments! 🙂 

Btw: I am using Sort Everything on a daily basis for the last few weeks and beside this bug it's been working flawlessly!
