### ISSUE TITLE
Sorting forces string wrapping - how to disable?

### ISSUE THREAD

**Issue by jgspratt** [bennycode/sort-everything#13]
I generally do not like my YAML strings to be wrapped, however `sort-everything` automatically wraps my strings at column 82.  

For example:

```
terraform:
  zz: asdf
  url: "https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip"
```

Becomes:

```
terraform:
  url: "https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd6\
    4.zip"
  zz: asdf
```

Other methods of sorting these lines (from other extensions) do not enforce this, although I prefer the sorting algorithm of `sort-everything`.

Could you introduce a setting to disable this feature?
