### ISSUE TITLE
Bug: When I select values in a YAML list then they are not sorted properly

### ISSUE THREAD

**Issue by bennycode** [bennycode/sort-everything#26]
This is my YAML file:

```yaml
resourceServers:
  - allow_offline_access: true
    enforce_policies: true
    identifier: https://bennycode.com/
    name: Logical API
    scopes:
      - value: abc:read
      - value: abc:manage
      - value: abc:edit
      - value: abc:view
```

When I select the values in the "scopes" section and try to sort them, then these are not sorted.

I want this:

```yaml
      - value: abc:read
      - value: abc:manage
      - value: abc:edit
      - value: abc:view
```

To become this:

```yaml
      - value: abc:edit
      - value: abc:manage
      - value: abc:read
      - value: abc:view
``` 

It works when being sorted in a `.txt` file but not in a `.yaml` file.
